on: ['push', 'pull_request']

name: Tox sanity test

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Tox test
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox
      uses: encukou/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py36, py37, py38, py39, pypy3]
